import Head from 'next/head'
import Layout from '../../components/Layout';
import Card from "@mui/material/Card";
import CardContent from "@mui/material/CardContent";
import Box from "@mui/material/Box";
import React from 'react';
import Grid from "@mui/material/Grid";
import classes from '../styles/Home.module.css'
import Timeline from '../../components/Timeline';
import Table from "@mui/material/Table";
import TableBody from "@mui/material/TableBody";
import TableCell from "@mui/material/TableCell";
import TableContainer from "@mui/material/TableContainer";
import TableHead from "@mui/material/TableHead";
import TableRow from "@mui/material/TableRow";
import Paper from "@mui/material/Paper";
import RoleItem from '../../components/RoleItem';
import Checkbox from "@mui/material/Checkbox";
import { FormControl, FormControlLabel, FormGroup, InputLabel, MenuItem, Select } from '@mui/material';

const Home = () => {
    const [state, setState] = React.useState({
      gilad: true,
      jason: false,
      antoine: false,
    });

    const handleChangeChecked = (event) => {
      setState({
        ...state,
        [event.target.name]: event.target.checked,
      });
    };

    const { gilad, jason, antoine } = state;
  const [age, setAge] = React.useState("");

  const handleChange = (event) => {
    setAge(event.target.value);
  };

  const rows = [
    {
      roleName: "admin",
      access: [
        {
          candidate: ["c", "r", "u", "d"],
        },
        {
          kepanitiaan: ["c", "r", "u"],
        },
      ],
    },
    {
      roleName: "pengurus_harian",
      access: [
        {
          candidate: ["c", "r", "u", "d"],
        },
        {
          kepanitiaan: ["c", "r"],
        },
        
      ],
    },
  ];
  return (
    <div style={{ position: "relative" }}>
      <Head>
        <title>Dashboard | Pemilra FTI UAJY</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <Box sx={{ flexGrow: 1 }} style={{ padding: "2rem" }}>
          <Grid
            container
            spacing={{ xs: 2, md: 3 }}
            columns={{ xs: 4, sm: 8, md: 12 }}
          >
            <Grid item xs={12} sm={12} md={4} key="1">
              <Card variant="outlined">
                <React.Fragment>
                  <CardContent>
                    <h3 className="sub_title_content">
                      Cara menggunakan dashboard ini
                    </h3>
                    <p className={classes.sub_title}>
                      Ikuti langkah berikut untuk dapat menggunakan dashboard
                      Pemilra FTI UAJY
                    </p>
                    <div className={classes.main_content}>
                      <Timeline></Timeline>
                    </div>
                  </CardContent>
                </React.Fragment>
              </Card>
            </Grid>
            <Grid item xs={12} sm={12} md={4} key="1">
              <Card variant="outlined">
                <React.Fragment>
                  <CardContent>
                    <h3
                      className="sub_title_content"
                      style={{ marginBottom: "1rem" }}
                    >
                      Role
                    </h3>
                    <div style={{ display: "flex", flexWrap: "wrap" }}>
                      <div>
                        <TableContainer variant="outlined" component={Paper}>
                          <Table aria-label="simple table">
                            <TableHead>
                              <TableRow>
                                <TableCell>
                                  <b>Role Name</b>
                                </TableCell>
                                <TableCell>
                                  <b>Access</b>
                                </TableCell>
                                <TableCell>
                                  <b></b>
                                </TableCell>
                              </TableRow>
                            </TableHead>
                            <TableBody>
                              {rows.map((row) => (
                                <TableRow
                                  key={row.roleName}
                                  sx={{
                                    "&:last-child td, &:last-child th": {
                                      border: 0,
                                    },
                                  }}
                                >
                                  <TableCell
                                    component="th"
                                    scope="row"
                                    key={row.roleName}
                                  >
                                    {row.roleName}
                                  </TableCell>
                                  <TableCell>
                                    {row.access.map((ro) => (
                                      <RoleItem
                                        key={row.roleName + "_" + ro}
                                        access={ro}
                                      ></RoleItem>
                                    ))}
                                  </TableCell>
                                </TableRow>
                              ))}
                            </TableBody>
                          </Table>
                        </TableContainer>
                      </div>
                    </div>
                  </CardContent>
                </React.Fragment>
              </Card>
            </Grid>
            <Grid item xs={12} sm={12} md={4} key="1">
              <Card variant="outlined">
                <React.Fragment>
                  <CardContent>
                    <h3
                      className="sub_title_content"
                      style={{ marginBottom: "1rem" }}
                    >
                      Role
                    </h3>
                    <div>
                      <Card variant="outlined">
                        <CardContent>
                          <form
                            action="/send-data-here"
                            method="post"
                            className={classes.form}
                          >
                            <div className={classes.form_label}>
                              <label
                                className={classes.label}
                                htmlFor="nama_role"
                              >
                                <h2 className={classes.label_inner}>
                                  Nama Role
                                </h2>
                              </label>
                              <input
                                className={classes.input}
                                type="text"
                                id="nama_role"
                                name="nama_role"
                                placeholder="Masukkan Nama Role"
                              />
                            </div>
                            <div className={classes.form_label}>
                              <FormControl size="small" fullWidth>
                                <InputLabel id="demo-simple-select-label">
                                  Fitur
                                </InputLabel>

                                <Select
                                  labelId="demo-simple-select-label"
                                  id="demo-simple-select"
                                  value={age}
                                  label=""
                                  onChange={handleChange}
                                >
                                  <MenuItem value={"kandidat"}>
                                    Kandidat
                                  </MenuItem>
                                  <MenuItem value={"timeline"}>
                                    Timeline
                                  </MenuItem>
                                  <MenuItem value={"periode"}>Periode</MenuItem>
                                  <MenuItem value={"organisasi"}>
                                    Organisasi
                                  </MenuItem>
                                  <MenuItem value={"users"}>Users</MenuItem>
                                </Select>
                              </FormControl>
                            </div>
                            <FormGroup>
                              <h2
                                className={classes.label_inner}
                                style={{ marginTop: "1rem" }}
                              >
                                Akses
                              </h2>
                              <FormControlLabel
                                control={
                                  <Checkbox
                                    checked={gilad}
                                    onChange={handleChangeChecked}
                                    name="gilad"
                                  />
                                }
                                label="Create"
                              />
                              <FormControlLabel
                                control={
                                  <Checkbox
                                    checked={gilad}
                                    onChange={handleChangeChecked}
                                    name="gilad"
                                  />
                                }
                                label="Read"
                              />
                              <FormControlLabel
                                control={
                                  <Checkbox
                                    checked={gilad}
                                    onChange={handleChangeChecked}
                                    name="gilad"
                                  />
                                }
                                label="Update"
                              />
                              <FormControlLabel
                                control={
                                  <Checkbox
                                    checked={jason}
                                    onChange={handleChangeChecked}
                                    name="jason"
                                  />
                                }
                                label="Delete"
                              />
                            </FormGroup>
                            <div className={classes.form_label}>
                              <button className={classes.submit} type="submit">
                                Submit
                              </button>
                            </div>
                          </form>
                        </CardContent>
                      </Card>
                    </div>
                  </CardContent>
                </React.Fragment>
              </Card>
            </Grid>
            <Grid item xs={12} sm={12} md={6} key="1">
              <Card variant="outlined">
                <React.Fragment>
                  <CardContent>
                    <h3 className="sub_title_content">
                      Cara menggunakan dashboard ini
                    </h3>
                    <p className={classes.sub_title}>
                      Ikuti langkah berikut untuk dapat menggunakan dashboard
                      Pemilra FTI UAJY
                    </p>
                    <div className={classes.main_content}>
                      <Timeline></Timeline>
                    </div>
                  </CardContent>
                </React.Fragment>
              </Card>
            </Grid>
            <Grid item xs={12} sm={12} md={6} key="1">
              <Card variant="outlined">
                <React.Fragment>
                  <CardContent>
                    <h3 className="sub_title_content">
                      Cara menggunakan dashboard ini
                    </h3>
                    <p className={classes.sub_title}>
                      Ikuti langkah berikut untuk dapat menggunakan dashboard
                      Pemilra FTI UAJY
                    </p>
                    <div className={classes.main_content}>
                      <Timeline></Timeline>
                    </div>
                  </CardContent>
                </React.Fragment>
              </Card>
            </Grid>
            <Grid item xs={12} sm={12} md={6} key="1">
              <Card variant="outlined">
                <React.Fragment>
                  <CardContent>
                    <h3 className="sub_title_content">
                      Cara menggunakan dashboard ini
                    </h3>
                    <p className={classes.sub_title}>
                      Ikuti langkah berikut untuk dapat menggunakan dashboard
                      Pemilra FTI UAJY
                    </p>
                    <div className={classes.main_content}>
                      <Timeline></Timeline>
                    </div>
                  </CardContent>
                </React.Fragment>
              </Card>
            </Grid>
            <Grid item xs={12} sm={12} md={6} key="1">
              <Card variant="outlined">
                <React.Fragment>
                  <CardContent>
                    <h3 className="sub_title_content">
                      Cara menggunakan dashboard ini
                    </h3>
                    <p className={classes.sub_title}>
                      Ikuti langkah berikut untuk dapat menggunakan dashboard
                      Pemilra FTI UAJY
                    </p>
                    <div className={classes.main_content}>
                      <Timeline></Timeline>
                    </div>
                  </CardContent>
                </React.Fragment>
              </Card>
            </Grid>
            <Grid item xs={12} sm={12} md={6} key="1">
              <Card variant="outlined">
                <React.Fragment>
                  <CardContent>
                    <h3 className="sub_title_content">
                      Cara menggunakan dashboard ini
                    </h3>
                    <p className={classes.sub_title}>
                      Ikuti langkah berikut untuk dapat menggunakan dashboard
                      Pemilra FTI UAJY
                    </p>
                    <div className={classes.main_content}>
                      <Timeline></Timeline>
                    </div>
                  </CardContent>
                </React.Fragment>
              </Card>
            </Grid>
            <Grid item xs={12} sm={12} md={6} key="1">
              <Card variant="outlined">
                <React.Fragment>
                  <CardContent>
                    <h3 className="sub_title_content">
                      Cara menggunakan dashboard ini
                    </h3>
                    <p className={classes.sub_title}>
                      Ikuti langkah berikut untuk dapat menggunakan dashboard
                      Pemilra FTI UAJY
                    </p>
                    <div className={classes.main_content}>
                      <Timeline></Timeline>
                    </div>
                  </CardContent>
                </React.Fragment>
              </Card>
            </Grid>
          </Grid>
        </Box>
      </Layout>
    </div>
  );
}

export default Home